# -*- mode: ruby -*-
# vi: set ft=ruby :

brew "bazel"
brew "python@3.10"
brew "tidy-html5"
brew "scipy"  # See #496.  We use brew instead of pip because bazel's pip was installing an incompatible numpy@1.21.6 (into /opt/homebrew/lib/python3.10/site-packages/) if scipy was listed in requirements.txt
