#!/bin/bash

# Copyright 2017 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -eux

export DEBIAN_FRONTEND=noninteractive

yes | ./scripts/setup/ubuntu/18.04/install_prereqs

set +u
if [ -z "${DRAKE_BINARY_URL}" ]; then
    DRAKE_BINARY_URL=`python3 -c "import sys, json; drake = json.load(open('drake_version.json')); print(drake['base_url'] + drake['build'] + '/drake-' + drake['version'] + '-bionic.tar.gz')"`
fi
set -u

pushd /opt

wget -nv -O drake.tar.gz "${DRAKE_BINARY_URL}"
tar -xzf drake.tar.gz
rm -f drake.tar.gz

cat /opt/drake/share/doc/drake/VERSION.TXT && echo ""

yes | /opt/drake/share/drake/setup/install_prereqs

popd


