#!/bin/bash

# Copyright 2017 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -eux

./scripts/setup/mac/install_prereqs

# load drake url from json
readonly drake_url=`python3 -c "import sys, json; drake = json.load(open('drake_version.json')); print(drake['base_url'] + drake['build'] + '/drake-' + drake['mac_version'] + '-mac.tar.gz')"`

pushd /usr/local

curl -LsSO -m 60 -o drake.tar.gz --retry 4 --retry-delay 0 "${drake_url}"
tar -xzf drake.tar.gz
rm -f drake.tar.gz

cat ./drake/share/doc/drake/VERSION.TXT

./drake/share/drake/setup/install_prereqs

popd
