#!/bin/bash

# Copyright 2017 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -eux

cmake --version

mkdir build
pushd build

cmake -Ddrake_DIR=/opt/drake/lib/cmake/drake ..
make
ctest -V .

rm -rf build

popd

