#!/bin/zsh

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

export HOMEBREW_NO_ANALYTICS=1 HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=1

./scripts/setup/mac/install_prereqs
trap 'brew cleanup && rm -rf "$(brew --cache)"' EXIT

pushd /tmp
curl -LsSO -m 60 --retry 4 --retry-delay 0 https://drake-packages.csail.mit.edu/drake/continuous/drake-latest-mac.tar.gz
popd
trap 'brew cleanup && rm -rf /tmp/drake-latest-mac.tar.gz "$(brew --cache)"' EXIT
pushd /opt
sudo tar -xf /tmp/drake-latest-mac.tar.gz
popd

export HOMEBREW_CURL_RETRIES=4

brew bundle --file=/opt/drake/share/drake/setup/Brewfile --no-lock
