#!/bin/zsh

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

bazel test --jobs=1 --keep_going //...
