#!/bin/bash

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

git submodule sync --recursive
set +x
git -c "http.extraheader=$(git config --local --get http.https://github.com/.extraheader)" \
  -c protocol.version=2 submodule update -f --depth 1 --init --recursive
