#!/bin/bash

# Copyright 2017 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -eux

./scripts/continuous_integration/common/drake_cmake_external
./scripts/continuous_integration/common/drake_cmake_installed
