# Underactuated core library. For drake_models data, run setup/fetch_drake_models.sh
# or set DRAKE_MODELS_PATH at runtime.
python_sources(
    dependencies=[
        "//:reqs#drake",
        "//:reqs#ipython",
        "//:reqs#ipywidgets",
        "//:reqs#lxml",
        "//:reqs#matplotlib",
        "//:reqs#mpld3",
        "//:reqs#scipy",
    ],
)
