#!/bin/bash

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

bazel test --cache_test_results=no --discard_analysis_cache=yes \
  --jobs=1 --keep_going=yes --keep_state_after_build=no --repository_cache= \
  --test_summary=detailed --test_verbose_timeout_warnings=yes \
  --track_incremental_state=no --verbose_failures=yes \
  --verbose_test_summary=yes //...
