#!/bin/bash

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

bazel test --discard_analysis_cache=yes --jobs=1 --keep_going=yes \
  --keep_state_after_build=no --test_summary=detailed \
  --test_verbose_timeout_warnings=yes --track_incremental_state=no \
  --verbose_test_summary=yes //...
